groups:
  - name: my-rules
    rules: 
    - alert: GoDirectionAppDown
      expr: up{job="go-direction-app"} == 0
      for: 1m
# recording rules are present to give a label name to the rules
    - record: job:app_response_latency_seconds:rate1m
      expr: rate(app_response_latency_seconds_sum[1m]) / rate(app_response_latency_seconds_count[1m])
# Once the rules are created now it can be used under alert section
    - alert: AppLatencyAbove5sec
      expr: job:app_response_latency_seconds:rate1m >= 5
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: 'Python app latency is over 5 seconds'
        description: 'App latency of instance {{ $labels.instance }} of job {{ $labels.job }} is {{ $value }} 
        for more than 5 mins'
        app_link: 'http://localhost:8080/'