/*
 * Weight Tracker API
 *
 * API for inserting a person's weight record.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse400 struct {
	Error_ string `json:"error,omitempty"`
}
